Improve error message

diff --git a/load-terminologies-metadata b/load-terminologies-metadata
--- a/load-terminologies-metadata
+++ b/load-terminologies-metadata
@@ -1,5 +1,7 @@
 #!/usr/bin/bash
 set -euo pipefail
+function error() { echo $@ >&2; exit 1; }
 
-echo "Loading N4O Terminologies Metadata into the Knowledge Graph"
-./load-rdf-graph https://graph.nfdi4objects.net/terminology/ stage/terminology/terminologies.ttl
+echo -n "Loading N4O Terminologies Metadata into the Knowledge Graph"
+./load-rdf-graph https://graph.nfdi4objects.net/terminology/ stage/terminology/terminologies.ttl || error "FAILED"
+echo OK
