Extend test script

diff --git a/load-collection-metadata b/load-collection-metadata
--- a/load-collection-metadata
+++ b/load-collection-metadata
@@ -2,17 +2,12 @@
 set -euo pipefail
 
 function usage() {
-    echo "Usage: $0 COLLECTION_ID [--issued]"
-    echo "Update description about a collection in Fuseki."
-    echo "Option --issued updates dct:issued with current timestamp."
+    echo "Usage: $0 COLLECTION_ID"
+    echo "Update description about a collection in triple store."
     exit
 }
 
-issued=${2:-}
-
 [[ "${1:-}" =~ ^[0-9]*$ ]] || usage
-[[ $# -le 2 ]] || usage
-[[ $# -eq 2 ]] && [[ "$issued" != "--issued" ]] && usage
 
 function error() {
     echo $@ >&2
@@ -22,13 +17,13 @@ function error() {
 id=$1
 uri=https://graph.nfdi4objects.net/collection/$id
 
-collection=stage/collection/$id/collection.json
-about=$(npm run --silent -- jsonld2rdf -c collection-context.json $collection)
+collection=stage/collection/$id/collection.nt
+[[ -s "$collection" ]] || error "Missing or empty $collection"
 
-[[ -z "$about" ]] && error "Missing $uri in $collections"
+issued=$(date -Iminutes)
 
-filter="FILTER (?p != dct:issued)"
-[[ -z "$issued" ]] || filter="" 
+# check whether API is available
+./sparql-update "INSERT DATA {}" || error "SPARQL Update endpoint not available!"
 
 echo "Deleting metadata of $uri"
 sparql=$(cat <<-SPARQL
@@ -40,15 +35,11 @@ WHERE {
   { VALUES ?s { n4oc:$id } ?s ?p ?o }
   UNION
   { VALUES ?o { n4oc:$id } ?s ?p ?o } 
-  $filter
 }
 SPARQL
 )
 
-# echo "$sparql"
 ./sparql-update "$sparql"
-
-[[ ! -z "$issued" ]] && issued="<$uri> dct:issued \"$(date -Iminutes)\"^^xsd:dateTime ."
     
 echo "Adding new metadata of $uri"
 sparql=$(cat <<-SPARQL
@@ -56,13 +47,12 @@ PREFIX dct: <http://purl.org/dc/terms/>
 PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
 PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
 INSERT DATA { GRAPH <https://graph.nfdi4objects.net/collection/> {
-$about
-<$uri> skos:notation "$id" .
-$issued
+$(< $collection)
+<$uri> dct:issued "$issued"^^xsd:dateTime .
 } }
 SPARQL
 )
 
-# echo "$sparql"
+#echo "$sparql"
 ./sparql-update "$sparql"
 
